<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>76982cc9-7998-47ce-9e9a-59254c2ff74d</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
		<PackageReference Include="Aspire.Hosting.MongoDB" Version="9.3.0" />
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WishListApp\WishListApp.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Keycloak\Resources\wishlist-dev-realm.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
