<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>679953be-6350-4678-83e8-611ceb0cc055</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.2" />
		<PackageReference Include="Aspire.Hosting.MongoDB" Version="13.0.2" />
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WishListApp\WishListApp.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Keycloak\Resources\wishlist-dev-realm.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
