<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>3f27ba78-b92b-4585-8ae0-cf6fc01cfa93</UserSecretsId>
		<RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup>
		<AdditionalFileItemNames>$(AdditionalFileItemNames);EmbeddedResource</AdditionalFileItemNames>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WishListApp.Data\WishListApp.Data.csproj" />
		<ProjectReference Include="..\WishListApp.ProductCrawling\WishListApp.ProductCrawling.csproj" />
		<ProjectReference Include="..\WishListApp.ServiceDefaults\WishListApp.ServiceDefaults.csproj" />
		<ProjectReference Include="..\SharedLibraries\src\Blazor\Shared.Blazor.Dialogs\Shared.Blazor.Dialogs.csproj" />
		<ProjectReference Include="..\SharedLibraries\src\Blazor\Shared.Blazor.SourceGeneration\Shared.Blazor.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.0" />
	</ItemGroup>

</Project>
