using System.Text;
using Microsoft.CodeAnalysis;
using WishListApp.SourceGeneration.LocalizationServiceGenerator.Models;

namespace WishListApp.SourceGeneration.LocalizationServiceGenerator.Generators;

internal static class ClassGenerator
{
    public static void GenerateLocalizationServiceClass(
        SourceProductionContext context,
        (LocalizationService service, Resource? Resource) serviceAndResource)
    {
        var (service, resource) = serviceAndResource;

        var @namespace = service.Namespace is not null
            ? $"global::{service.Namespace}."
            : "global::";

        var localizationType = $"{@namespace}{service.Name}";

        var builder = new StringBuilder();

        builder.AppendLine(
            $$"""
            // <auto-generated/>
            
            #nullable enable

        
            """);


        if (!string.IsNullOrEmpty(service.Namespace))
        {
            builder.AppendLine(
                $$"""
                namespace {{service.Namespace}};

                """);
        }

        builder.AppendLine(
            $$"""
            partial class {{service.Name}}
            {
                public sealed class LocalizationService(
                    global::Microsoft.Extensions.Localization.IStringLocalizer<{{localizationType}}> localizer)
                    : ILocalizationService
                {
                    private readonly global::Microsoft.Extensions.Localization.IStringLocalizer<{{localizationType}}> _localizer = localizer;
            """);

        if (resource is null)
        {
            builder.AppendLine(
                $$"""

                        // Error: Resource file not found
                """);
        }
        else if (resource.Error is not null)
        {
            builder.AppendLine(
                $$"""

                        // Error: {{resource.Error}}
                """);
        }
        else
        {
            foreach (var name in resource.Names)
            {
                builder.AppendLine(
                    $$"""

                            public string {{name}} => _localizer["{{name}}"];
                    """);
            }
        }

        builder.AppendLine(
            """
                }
            }
            """);

        context.AddSource($"{service.Name}_LocalizationService.g.cs", builder.ToString());
    }
}
