using System.Text;
using Microsoft.CodeAnalysis;
using WishListApp.SourceGeneration.LocalizationServiceGenerator.Models;

namespace WishListApp.SourceGeneration.LocalizationServiceGenerator.Generators;

internal static class ClassGenerator
{
    public static void GenerateLocalizationServiceClass(
        SourceProductionContext context,
        (LocalizationService service, Resource? Resource) serviceAndResource)
    {
        var (service, resource) = serviceAndResource;

        var @namespace = service.Namespace is not null
            ? $"global::{service.Namespace}."
            : "global::";

        var localizationType = $"{@namespace}{service.Name}";

        var builder = new StringBuilder();

        builder.AppendLine(
            $$"""
            // <auto-generated/>

            #nullable enable

        
            """);


        if (!string.IsNullOrEmpty(service.Namespace))
        {
            builder.AppendLine(
                $$"""
                namespace {{service.Namespace}};

                """);
        }

        builder.AppendLine(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Constants.Namespace}}", "1.0.0")]
            public sealed class LocalizationService_{{service.Name}}(
                global::Microsoft.Extensions.Localization.IStringLocalizer<{{localizationType}}> localizer)
                : {{@namespace}}ILocalizationService_{{service.Name}}
            {
                private readonly global::Microsoft.Extensions.Localization.IStringLocalizer<{{localizationType}}> _localizer = localizer;
            """);

        if (resource is null)
        {
            builder.AppendLine(
                $$"""

                    // Error: Resource file not found
                """);
        }
        else if (resource.Error is not null)
        {
            builder.AppendLine(
                $$"""

                    // Error: {{resource.Error}}
                """);
        }
        else
        {
            foreach (var name in resource.Names)
            {
                builder.AppendLine(
                    $$"""

                        public string {{name}} => _localizer["{{name}}"];
                    """);
            }
        }

        builder.AppendLine("}");

        context.AddSource($"LocalizationService_{service.Name}.g.cs", builder.ToString());
    }
}
