using System.Text;
using Microsoft.CodeAnalysis;
using WishListApp.SourceGeneration.LocalizationServiceGenerator.Models;

namespace WishListApp.SourceGeneration.LocalizationServiceGenerator.Generators;

internal static class InterfaceGenerator
{
    public static void GenerateLocalizationServiceInterface(
        SourceProductionContext context,
        (LocalizationService service, Resource? Resource) serviceAndResource)
    {
        var (service, resource) = serviceAndResource;

        var builder = new StringBuilder();

        builder.AppendLine(
            $$"""
            // <auto-generated/>

            #nullable enable

        
            """);


        if (!string.IsNullOrEmpty(service.Namespace))
        {
            builder.AppendLine(
                $$"""
                namespace {{service.Namespace}};

                """);
        }

        builder.Append(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Constants.Namespace}}", "1.0.0")]
            public interface ILocalizationService_{{service.Name}}
            {
            """);

        if (resource is null)
        {
            builder.AppendLine(
                $$"""

                    // Error: Resource file not found
                """);
        }
        else if (resource.Error is not null)
        {
            builder.AppendLine(
                $$"""

                    // Error: {{resource.Error}}
                """);
        }
        else
        {
            foreach (var name in resource.Names)
            {
                builder.AppendLine(
                    $$"""

                        string {{name}} { get; }
                    """);
            }
        }

        builder.AppendLine("}");

        context.AddSource($"ILocalizationService_{service.Name}.g.cs", builder.ToString());
    }
}
