hostname:
mongodb:
  name: "mongodb"
  version: "7.0.12"
  members: 3
  caConfigMapName: "selfsigned-ca"
  resources:
    mongod:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 200m
        memory: 500Mi
    mongodbAgent:
      requests:
        cpu: 50m
        memory: 50M
      limits:
        cpu: 200m
        memory: 200M
    mongodbAgentReadinessProbe:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
app:
  image: harbor.damidhagor.de/wishlist/wishlist-app
  tag: "latest"
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 600Mi
aspire:
  image: "aspire-dashboard"
  tag: "8.1.0"
  otlpEndpoint: "http://aspire-dashboard:4317"
