apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: wishlist-app
spec:
  selector:
    matchLabels:
      app: wishlist-app
  template:
    metadata:
      labels:
        app: wishlist-app
    spec:
      containers:
        - name: wishlist-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ConnectionStrings__MongoDB
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-wishlist-app
                  key: connectionString.standardSrv
            - name: ApplicationUrl
              value: "https://{{ .Values.hostname }}"
            - name: IdentityOptions__Authority
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: identity-authority
            - name: IdentityOptions__ClientId
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: identity-client-id
            - name: IdentityOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: identity-client-secret
            - name: IdentityOptions__Scopes
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: identity-scopes
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otel.collector }}"
          volumeMounts:
            - name: selfsigned-ca
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
      volumes:
        - name: selfsigned-ca
          configMap:
            name: selfsigned-ca
      imagePullSecrets:
        - name: harbor
