apiVersion: v1
kind: Service
metadata:
  name: wishlist-app
  namespace: {{ Release.Namespace }}
spec:
  selector:
    app: wishlist-app
  ports:
  - name: wishlist-app
    protocol: TCP
    port: 8080
    targetPort: 8080
