apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: wishlist-app
spec:
  selector:
    matchLabels:
      app: wishlist-app
  template:
    metadata:
      labels:
        app: wishlist-app
    spec:
      containers:
        - name: wishlist-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ConnectionStrings__mongodb
              valueFrom:
                secretKeyRef:
                  name: wishlist-app
                  key: mongodbConnectionString
            - name: MongoDBDatabaseName
              valueFrom:
                secretKeyRef:
                  name: wishlist-app
                  key: mongodbDatabaseName
            - name: ApplicationUrl
              value: "https://{{ .Values.hostname }}"
            - name: IdentityOptions__Authority
              valueFrom:
                secretKeyRef:
                  name: wishlist-app
                  key: oidcAuthority
            - name: IdentityOptions__ClientId
              valueFrom:
                secretKeyRef:
                    name: wishlist-app
                    key: oidcClientId
            - name: IdentityOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                    name: wishlist-app
                    key: oidcClientSecret
            - name: IdentityOptions__Scopes
              valueFrom:
                secretKeyRef:
                    name: wishlist-app
                    key: oidcScopes
            {{- if .Values.otlpEndpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otlpEndpoint }}"
            {{- end }}
          {{- if .Values.app.resources }}
          resources: {{ .Values.app.resources | toYaml | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: harbor