apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: wishlist-{{ .Values.environment }}
type: Opaque
data:
  identity-authority:
  identity-client-id:
  identity-client-secret:
  identity-scopes:
  