apiVersion: batch/v1
kind: Job
metadata:
  name: wishlist-cli-migration
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: wishlist-cli-migration
        image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["dotnet", "WishlistApp.Cli.dll", "database", "apply-migrations", "-c", "$(connectionstring)"]
        env:
        - name: connectionstring
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string
      restartPolicy: Never
      imagePullSecrets:
        - name: harbor
