apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  secretName: mongodb-certificate
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
  duration: "8760h" # 365 days
  renewBefore: "720h" # 30 days
  commonName: "*.{{ .Values.mongodb.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
  dnsNames:
    - "*.{{ .Values.mongodb.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
