kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ Release.Namespace }}
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.size }}
