global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MongoDB.Bson;
global using MongoDB.Driver;
global using MongoDB.Driver.Linq;
global using OneOf;
global using WishListApp.Data.Models;
global using WishListApp.Data.Repositories;
global using WishListApp.Data.Services;
