name: Publish To Harbor

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version of the application'
        required: true
      platforms:
        description: 'The Docker platforms to build'
        required: true
        default: 'linux/amd64,linux/arm64'

jobs:
  build-wishlist-app:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        file: src/WishListApp/Dockerfile
        platforms: ${{ inputs.platforms }}
        tags: ghcr.io/${{ github.actor }}/wishlist-app:${{ inputs.version }}
        push: true

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ghcr.io/${{ github.actor }}/wishlist-app
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
        
  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: [build-wishlist-app]
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Replace Version in values.yaml
      run: "sed -i \"s/tag: \"latest\"/tag: \"${{ inputs.version }}\"/g\" helm/wishlist/values.yaml"

    - name: Helm Setup
      uses: azure/setup-helm@v4

    - name: Helm Login
      run: helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Helm Package
      run: helm package helm/wishlist --app-version "${{ inputs.version }}"

    - name: Helm Push
      run: helm push wishlist-*.tgz oci://ghcr.io/${{ github.actor }}
