name: Publish To Harbor

on:
  push:
    branches: 
    - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version of the application'
        required: true
        default: ''

jobs:
  build-wishlist-app:
    runs-on: ubuntu-latest

    steps:
    - name: Create Version Number
      id: version
      run: |
        if [ "${{ inputs.version }}" != '' ]; then
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT;
        else
          echo "version=${{ github.run_id }}" >> $GITHUB_OUTPUT;
        fi
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Harbor Login
      uses: docker/login-action@v3.0.0
      with:
        registry: harbor.damidhagor.de
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: "{{defaultContext}}:src"
        file: WishListApp/Dockerfile
        tags: harbor.damidhagor.de/wishlist/wishlist-app:${{ steps.version.outputs.version }}, harbor.damidhagor.de/wishlist/wishlist-app:latest
        push: true
        
  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: [build-wishlist-app]

    steps:
    - name: Create Version Number
      id: version
      run: |
        if [ "${{ inputs.version }}" != '' ]; then
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT;
        else
          echo "version=${{ github.run_id }}" >> $GITHUB_OUTPUT;
        fi
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Replace Version in values.yaml
      run: "sed -i \"s/tag: \"latest\"/tag: \"${{ steps.version.outputs.version }}\"/g\" helm/wishlist/values.yaml"
    - name: Helm Setup
      uses: azure/setup-helm@v4
    - name: Helm Login
      run: helm registry login harbor.damidhagor.de -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_ACCESS_TOKEN }}
    - name: Helm Package
      run: helm package helm/wishlist --app-version "${{ steps.version.outputs.version }}"
    - name: Helm Push
      run: ls -la && helm push wishlist-*.tgz oci://harbor.damidhagor.de/wishlist
