name: Publish To Harbor

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version of the application'
        required: true
      platforms:
        description: 'The Docker platforms to build'
        required: true
        default: 'linux/amd64;linux/arm64'

jobs:
  build-wishlist-app:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v5

    - name: Docker Login  
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish and push Docker image
      run: |
        dotnet publish src/WishListApp \
          /t:PublishContainer \
          -p ContainerBaseImage=mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled-extra \
          -p RuntimeIdentifiers=${{ inputs.platforms }} \
          -p ContainerRuntimeIdentifiers=${{ inputs.platforms }} \
          -p ContainerRegistry=ghcr.io \
          -p ContainerRepository=${{ github.actor }}/wishlist-app \
          -p ContainerImageTag=${{ inputs.version }} \
          -v d
        
  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: [build-wishlist-app]
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Replace Version in values.yaml
      run: "sed -i \"s/tag: \"latest\"/tag: \"${{ inputs.version }}\"/g\" helm/wishlist/values.yaml"

    - name: Helm Setup
      uses: azure/setup-helm@v4

    - name: Helm Login
      run: helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Helm Package
      run: helm package helm/wishlist --app-version "${{ inputs.version }}"

    - name: Helm Push
      run: helm push wishlist-*.tgz oci://ghcr.io/${{ github.actor }}
