name: Publish To Harbor

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-wishlist-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Harbor Login
      uses: docker/login-action@v3.0.0
      with:
        registry: harbor.damidhagor.de
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: "{{defaultContext}}:src"
        file: WishlistApp/Dockerfile
        tags: harbor.damidhagor.de/wishlist/wishlist-app:${{ github.run_id }}, harbor.damidhagor.de/wishlist/wishlist-app:latest
        push: true
        
  build-wishlist-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: harbor.damidhagor.de
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: "{{defaultContext}}:src"
        file: WishlistApp.Cli/Dockerfile
        tags: harbor.damidhagor.de/wishlist/wishlist-cli:${{ github.run_id }}, harbor.damidhagor.de/wishlist/wishlist-cli:latest
        push: true
