name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    - name: Build App
      run: dotnet build src/WishListApp
    - name: Build Tests
      run: dotnet build src/WishListApp.Tests
    - name: Test
      run: dotnet test src/WishListApp.Tests
      
